global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'transcendence'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093'] # Use the service name

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['prometheus:9090'] # Use the service name

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:80'] # Use the service name and correct port

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']


# not working yet but I dont need to monitor this one do i ?
  # - job_name: 'portainer'
  #   scheme: https
  #   tls_config:
  #     insecure_skip_verify: true
  #   static_configs:
  #     - targets: ['portainer:9443']