server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: postgres_logs 
  static_configs:
    - targets:
        - localhost
      labels:
        job: postgres
        __path__: /var/lib/postgresql/data/log/postgresql.log
- job_name: redis_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: redis
      __path__: /var/log/redis/redis-server.log
- job_name: django_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: django
      __path__: /app/logs/django.log
- job_name: caddy_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: caddy
      __path__: /var/log/caddy/*log
      agent: caddy-promtail
  pipeline_stages:
  - json:
      expressions:
        duration: duration
        status: status
  - labels:
      duration:
      status: